name: Build & Publish

on:
  push:
    tags:
      - v*.*.*

env:
  JAVA_VERSION: 25
  BUILD_RELEASE: "true"
  CURSEFORGE_TOKEN: ${{ secrets.CURSEFORGE_TOKEN }}
  MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  AYAKA_MAVEN_TOKEN: ${{ secrets.AYAKA_MAVEN_TOKEN }}
  REPO: ${{ github.repository }}
  REPO_URL: "${{ github.server_url }}/${{ github.repository }}"
  DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
  TAG: ${{ github.ref_name }}

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check Environment Variables
        run: env

      - uses: actions/checkout@v6

      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: 'zulu'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5
        with:
          cache-read-only: true

      - name: Make Gradle Wrapper Executable
        if: ${{ runner.os != 'Windows' }}
        run: chmod +x ./gradlew

      - name: Build and Publish
        run: ./gradlew clean buildAndGather publishAll sendDiscord --no-daemon --warning-mode all --stacktrace
